# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourseSectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=4)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('Problem', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('maxMarks', models.IntegerField()),
                ('ProblemStatement', models.CharField(max_length=10000)),
                ('maxAttempts', models.IntegerField()),
                ('test_case_file', models.FileField(upload_to='D:/xampp/htdocs/se/Test_Case_File_Uploads/')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionId', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('DateTime', models.DateTimeField()),
                ('UserFileName', models.CharField(max_length=50)),
                ('UserFileNameUnique', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=10)),
                ('Marks', models.IntegerField()),
                ('LanguageUsed', models.CharField(max_length=10)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RegistrationId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=4)),
                ('NumberOfSuccessfulSubmission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProblemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Users'),
        ),
        migrations.AddField(
            model_name='solution',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student'),
        ),
        migrations.AddField(
            model_name='problem',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section'),
        ),
        migrations.AddField(
            model_name='facultycoursesectionrelation',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Users'),
        ),
    ]
