# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('FacultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('ProblemId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('maxMarks', models.IntegerField(max_length=10)),
                ('maxAttempts', models.IntegerField(max_length=10)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('ProblemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SectionId', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(max_length=10)),
                ('DateTime', models.DateTimeField()),
                ('UserFileName', models.CharField(max_length=50)),
                ('UserFileNameUnique', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=10)),
                ('Marks', models.IntegerField(max_length=10)),
                ('LanguageUsed', models.CharField(max_length=10)),
                ('ProblemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RegistrationId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email_id', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=4)),
                ('NumberOfSuccessfulSubmission', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProblemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(max_length=10)),
                ('ProblemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Problem')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Student'),
        ),
    ]
