# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='endTime',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='startTime',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
