# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Faculty')),
                ('SectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section')),
            ],
        ),
    ]
