# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0002_facultysectionrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Email_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
