# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0003_auto_20171025_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='maxAttempts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='maxMarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='Marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='attempt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentproblemrelation',
            name='attempt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
