# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0004_auto_20171025_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NumberOfSuccessfulSubmission',
            field=models.IntegerField(),
        ),
    ]
