# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0005_auto_20171025_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourseSectionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Course')),
                ('FacultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Faculty')),
                ('SectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section')),
            ],
        ),
        migrations.RemoveField(
            model_name='facultycourserelation',
            name='CourseId',
        ),
        migrations.RemoveField(
            model_name='facultycourserelation',
            name='FacultyId',
        ),
        migrations.RemoveField(
            model_name='facultysectionrelation',
            name='FacultyId',
        ),
        migrations.RemoveField(
            model_name='facultysectionrelation',
            name='SectionId',
        ),
        migrations.DeleteModel(
            name='FacultyCourseRelation',
        ),
        migrations.DeleteModel(
            name='FacultySectionRelation',
        ),
    ]
