# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0006_auto_20171028_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoursesectionrelation',
            name='Batch',
            field=models.CharField(default=2015, max_length=4),
            preserve_default=False,
        ),
    ]
