# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0007_facultycoursesectionrelation_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ProblemStatement',
            field=models.CharField(default='Find gcd of two numbers', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='Section',
            field=models.ForeignKey(default='CSE 2', on_delete=django.db.models.deletion.CASCADE, to='assignment_dashboard.Section'),
            preserve_default=False,
        ),
    ]
