# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0008_auto_20171030_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ProblemId',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
