# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_dashboard', '0009_auto_20171102_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_case_file',
            field=models.FileField(default=('sdfmgadsjfvbadsjfdbasfjsadb',), upload_to='D:/xampp/htdocs/se/Test_Case_File_Uploads/'),
            preserve_default=False,
        ),
    ]
